### ISSUE TITLE
automation: detekt를 프로젝트에 적용해야 합니다.

### ISSUE THREAD

**Issue by Revimal** [Gourmet-Dev/gourmet-service#2]
### 이슈 정보
* **기반 커밋:** Gourmet-Dev/gourmet-service@65a09617eccc2617a91d4c5a988a995db47d0a81

---
### 문제 상황
* 프로젝트에 코딩 스타일 검사가 존재하지 않음.

---
### 기대 상황
* Kotlin 공식 가이드 기반으로 코딩 스타일을 자동 검사할 수 있어야 함.

---
### 재현 조건
* 재현 조건 없음.

**Comment by Revimal** [comment]
### 확인 내용
* ktlint를 통해서 코딩 스타일 자동 검사하고, git-hook으로 commit시마다 검사하도록 적용.

**Comment by Revimal** [comment]
### 작업 계획
* [MS00001: gourmet-apis 마이그레이션 및 프로젝트 구성](https://github.com/Gourmet-Dev/gourmet-service/milestone/1)

**Comment by Revimal** [comment]
### 업데이트
* @dudgns0507 의 제안으로 [detekt](https://detekt.dev/)를 사용하는 것으로 진행

**Comment by dudgns0507** [comment]
모든 커밋에 적용하게 되면 lint 시간도 꽤 걸려서 커밋에는 적용하지 않고 pre-push에만 적용하는건 어떤지

**Comment by Revimal** [comment]
### 업데이트
* _https://github.com/Gourmet-Dev/gourmet-service/issues/10#issuecomment-1049431541_ 의 제안을 수용.
* 커밋 시에는 Ktlint를, Push 시에는 Detekt를 수행하게끔 PR 수정.

**Comment by Revimal** [comment]
### 처리 결과
#10 PR 반영되었고, 수정사항 검증 완료.
